name: Continuous Integration - CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "*/3 * * * *"

jobs:
  lint_continuous_integration:  # Changed hyphen to underscore for the job name
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to latest stable version

      - name: Set up Python
        uses: actions/setup-python@v3  # Updated to latest stable version
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install flake8
        run: pip install flake8

      - name: Install pylint
        run: pip install pylint

      - name: Lint with flake8
        run: flake8 .  # Running flake8 on all Python files in the repository

      - name: Lint with pylint
        run: pylint **/*.py  # Lint all Python files in the repository

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
